# Generated by Django 3.2 on 2023-01-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg', models.CharField(choices=[('Surprise Meal', 'Surprise Meal'), ('Bowls', 'Bowls'), ('Superbowls', 'Superbowls'), ('Pastas & Steaks', 'Pastas & Steaks'), ('Fit N Fab', 'Fit N Fab'), ('Thalis', 'Thalis'), ('Sandwiches', 'Sandwiches'), ('Wrapes', 'Wrapes'), ('Burgers', 'Burgers'), ('Appetizer', 'Appetizer'), ('Desserts', 'Desserts'), ('All Day Breakfast', 'All Day Breakfast'), ('Beverages', 'Beverages')], max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_product', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('product_image', models.ImageField(default=None, null=True, upload_to='images/')),
                ('price', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='sem_course.catagory')),
            ],
        ),
    ]
