# Generated by Django 4.1.7 on 2023-02-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booksmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('photo', models.ImageField(upload_to=None)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('des', models.CharField(max_length=500)),
            ],
        ),
    ]
