# Generated by Django 3.2.14 on 2023-02-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='photo',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
