# Generated by Django 3.2.14 on 2022-07-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('services', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
